---
title: "orderMCMC"
author: "Shengtong"
date: "2018-11-29"
output: workflowr::wflow_html
---


### listpossibleparents


```{r, echo=T}
combinations=function(n, r, v = 1:n, set = TRUE, repeats.allowed=FALSE)
{
  # n: number if remaining nodes 
  # r: number of parents 
  
  ###### this ensures n is a numeric, scale (length=1), greater than 1 and integer value 
  if(mode(n) != "numeric" || length(n) != 1 
     || n < 1 || (n %% 1) != 0) stop("bad value of n")   # %%: modulus (x mod y) 5%%2 is 1
  ##### same thing for r 
  if(mode(r) != "numeric" || length(r) != 1 
     || r < 1 || (r %% 1) != 0) stop("bad value of r") 
  #print(v)
  
  if(!is.atomic(v) || length(v) < n)  # ensure v is atomic and of the same length as n 
    stop("v is either non-atomic or too short")
  
  if( (r > n) & repeats.allowed==FALSE)  # number of maxparents MUST NOT exceed the remaining elements 
    stop("r > n and repeats.allowed=FALSE")
  
  if(set) {                               # always run this by the initial settings 
    v <- unique(sort(v))
    if (length(v) < n) stop("too few different elements") # again ensure length(v) is equal to n 
  }   # end of set 
  v0 <- vector(mode(v), 0)
  ## Inner workhorse
  if(repeats.allowed)
    sub <- function(n, r, v)
      { 
        if(r == 0) v0 else
        if(r == 1) matrix(v, n, 1) else
        if(n == 1) matrix(v, 1, r) else
        rbind( cbind(v[1], Recall(n, r-1, v)),
              Recall(n-1, r, v[-1]))
      }
  else
    ######################  ????? 
    sub <- function(n, r, v)  
      { 
        if(r == 0) v0 else  # no parents 
        if(r == 1) matrix(v, n, 1) else  # one parent 
        if(r == n) matrix(v, 1, n) else  # maximum number of parents 
        rbind(cbind(v[1], Recall(n-1, r-1, v[-1])),
              Recall(n-1, r, v[-1]))
    }
  
  sub(n, r, v[1:n])
}

listpossibleparents=function(maxparents,elements){

  listy<-vector("list",length(elements)) # generare a list with length of length(elements)

  for (i in elements){
    remainingelements<-elements[-i]

    matrixofparents<-rep(NA,maxparents)  
    for (r in 1:maxparents){
      possparents<-combinations(length(remainingelements),r,remainingelements)
      if(r<maxparents){
        for (j in 1:(maxparents-r)){
	  possparents <- cbind(possparents, NA)
        }
      }
    matrixofparents<-rbind(matrixofparents,possparents,deparse.level=0)
    } # end of r 
    
  listy[[i]] <- matrixofparents
  }   # end of i 

return(listy)
}
```


### scorepossibleparents


```{r, echo=T}
DAGcorescore=function(j,parentnodes,n){
  
  lp<-length(parentnodes) #number of parents
  return(lp)
}

TableDAGscore=function(parentrows, j, n){
	nrows<-nrow(parentrows)
	P_local <- numeric(nrows)   
   
	for (i in 1:nrows)  {
		parentnodes <- parentrows[i,which(parentrows[i,]>0)] # for every row, extract numeric values as parents 
		P_local[i]<-DAGcorescore(j,parentnodes,n)  # DAGcorescore is in numedgescore.R 
	}

return(P_local)
}

scorepossibleparents=function(parenttable,n){

  listy<-vector("list",n)

  for (j in 1:n){
    scoretemp<-TableDAGscore(parenttable[[j]], j, n)      # TableDAGscore is in scorefns.R 
    listy[[j]] <- as.matrix(scoretemp)
  }  

return(listy)

}
```





### example 

## orderscore

```{r, echo=T}
# parenttable a list of which every element is a matrix listing all possible parents in the row 
orderscore=function(n,scorenodes,parenttable,scoretable,permy){
  ###########
  #scorenodes=c(1:n)
  permy=currentpermy
  ###########
  orderscores<-rep(0,n)
  allscores<-vector("list",n) # define a list of length n 
  allowedscorerows<-vector("list",n)

  tablesize<-dim(parenttable[[1]]) # just to remove some arguments; list the number of rows and columns  

  ###################################
  ###################################
  ###### begin i
  # scorenodes=1:n
  # permy=currentpermy=startorder=c(1:n)
  for (i in scorenodes)
  {
 #   i=3
    position<-which(permy==i)
    if(position==n){ # no parents are allowed as root node starts from the right most 
	orderscores[i]<-scoretable[[i]][1,1]
	allscores[[i]]<-orderscores[i] # there is only one score
	allowedscorerows[[i]]<-c(1) # there is only one score
    } 
    ###############################
    else {
      if(position>1){  
	bannednodes<-permy[c(1:(position-1))]   # what is bannednodes?????? nodes comes before i, which could be offspring only!!! 
        allowedrows<-c(2:tablesize[1])
        for (j in 1:tablesize[2]){ # working columnwise allows R to speed up 
          bannedrows<-which(parenttable[[i]][allowedrows,j]%in%bannednodes)
	  if(length(bannedrows)>0){
	    allowedrows<-allowedrows[-bannedrows]
	  }
        }
	allowedrows<-c(1,allowedrows) # this row is always allowed because it is the case of no parents 
      	allscores[[i]]<-scoretable[[i]][allowedrows,1]
	allowedscorerows[[i]]<-allowedrows
      }  # end of if(position>1)
      #######################
      else{ # all parents are allowed
	allscores[[i]]<-scoretable[[i]][,1]
	allowedscorerows[[i]]<-c(1:tablesize[1]) # should exclude i itself? 
      }
      maxallowed<-max(allscores[[i]])
      orderscores[i]<-maxallowed+log(sum(exp(allscores[[i]]-maxallowed)))  # why order score is calculated this way?????? "By summing the scores of the permissble parent sets for each node" in the paper, but why "-maxallowed"? 
# it is used not for score calculationm but to normalzied the prob prob=exp(scores$allscores[[i]]-scores$totscores[i]) in samplescore function       
    }
    ##########################
  } # end of i
##############################
##############################  
  scores<-list()
  scores$allscores<-allscores
  scores$allowedrows<-allowedscorerows
  scores$totscores<-orderscores
return(scores)
}
```


### example 




```{r, echo=T}
maxparents=2
n=4
startorder<-c(1,3,4,2)
parenttable<-listpossibleparents(maxparents,c(1:n)) # list all possible parents for every node
tablelength<-nrow(parenttable[[1]]) # size of the table

# Now need to score them!

scoretable<-scorepossibleparents(parenttable,n) # number of parents in all possible cases    
currentpermy=startorder
order.score=orderscore(n,c(1:n),parenttable,scoretable,currentpermy)
order.score
```


## samplescore 

```{r, echo=T}
samplescore=function(n, scores)
{
 # scores=currentorderscores
  incidence<-matrix(numeric(n*n),nrow=n) # store the adjacency matrix
  sampledscore<-0
  for (i in 1:n){
   # i=1  # for every node i 
    scorelength<-length(scores$allscores[[i]])
    k<-sample.int(scorelength,1,prob=exp(scores$allscores[[i]]-scores$totscores[i])) # sample according to scores
    parentrow<-parenttable[[i]][scores$allowedrows[[i]][k],] # the parent set
    parentset<-parentrow[which(parentrow>0)] # removing NAs
    incidence[parentset,i]<-1 # fill in elements of the adjacency matrix
    sampledscore<-sampledscore+scores$allscores[[i]][k] # and add the score
  }
  DAG<-list()
  DAG$incidence<-incidence
  DAG$logscore<-sampledscore
  return(DAG)
  
}
```


### example 

```{r, echo=T}
currentorderscores<-orderscore(n,c(1:n),parenttable,scoretable,currentpermy)
currentorderscores
currentDAG<-samplescore(n,currentorderscores) #score of a single DAG sampled from the starting order
currentDAG
```



## orderMCMC

```{r, echo=T}
orderMCMC=function(n,startorder,iterations,stepsave,parenttable,scoretable,moveprobs){

  currentpermy<-startorder #starting order represented as a permutation
  currentorderscores<-orderscore(n,c(1:n),parenttable,scoretable,currentpermy) #starting score
  currenttotallogscore<-sum(currentorderscores$totscores) #log total score of all DAGs in the starting order

  currentDAG<-samplescore(n,currentorderscores) #score of a single DAG sampled from the starting order

  L1 <- list() # stores the adjacency matrix of a DAG sampled from the orders
  L2 <- list() # stores its log BGe score
  L3 <- list() # stores the log BGe score of the entire order
  L4 <- list() # stores the orders as permutations

  zlimit<- floor(iterations/stepsave) + 1 # number of outer iterations
  length(L1) <- zlimit
  length(L2) <- zlimit
  length(L3) <- zlimit
  length(L4) <- zlimit

  L1[[1]]<-currentDAG$incidence #starting DAG adjacency matrix
  L2[[1]]<-currentDAG$logscore #starting DAG score
  L3[[1]]<-currenttotallogscore #starting order score
  L4[[1]]<-currentpermy #starting order

  for (z in 2:zlimit){ #the MCMC chain loop with 'iteration' steps is in two parts
    for (count in 1:stepsave){ #since we only save the results to the lists each 'stepsave'

      chosenmove<-sample.int(3,1,prob=moveprobs)
      if(chosenmove<3){	# if it is 3 then we stay still
	
	proposedpermy<-currentpermy #sample a new order by swapping two elements
	switch(as.character(chosenmove),
	"1"={ # swap any two elements at random
	  sampledelements<-sample.int(n,2,replace=FALSE) #chosen at random
	},
	"2"={ # swap any adjacent elements
	  k<-sample.int(n-1,1) #chose the smallest at random
	  sampledelements<-c(k,k+1)
	},
	{# if neither is chosen, we have a problem
	  print('The move sampling has failed!')
	})
	proposedpermy[sampledelements]<-currentpermy[rev(sampledelements)] #proposed new order see rev functionn  ?rev 

	rescorenodes<-proposedpermy[min(sampledelements):max(sampledelements)] #we only need to rescore these nodes between the swapped elements to speed up the calculation

	proposedorderrescored<-orderscore(n,rescorenodes,parenttable,scoretable,proposedpermy) #their scores
	proposedtotallogscore<-currenttotallogscore-sum(currentorderscores$totscores[rescorenodes])+sum(proposedorderrescored$totscores[rescorenodes]) #and the new log total score by updating only the necessary nodes

	scoreratio<-exp(proposedtotallogscore-currenttotallogscore) #acceptance probability

	if(runif(1)<scoreratio){ #Move accepted then set the current order and scores to the proposal
		currentpermy<-proposedpermy
		currentorderscores$allowedrows[rescorenodes]<-proposedorderrescored$allowedrows[rescorenodes]
		currentorderscores$allscores[rescorenodes]<-proposedorderrescored$allscores[rescorenodes]
		currentorderscores$totscores[rescorenodes]<-proposedorderrescored$totscores[rescorenodes]
		currenttotallogscore<-proposedtotallogscore
	}
      }
    }
    currentDAG<-samplescore(n,currentorderscores)
    L1[[z]]<-currentDAG$incidence #store adjacency matrix of a sampled DAG each 'stepsave'
    L2[[z]]<-currentDAG$logscore #and log score of a sampled DAG
    L3[[z]]<-currenttotallogscore #and the current order score
    L4[[z]]<-currentpermy #and store current order
  }
  return(list(L1,L2,L3,L4))
}
```


## example 

```{r, echo=T}
n=3
startorder<-c(1:n) # starting order

maxparents<-2 # Maximum number of parents to allow

starttime<-proc.time() # for timing the problem

# Fill up a matrix with possible parents

parenttable<-listpossibleparents(maxparents,c(1:n))
tablelength<-nrow(parenttable[[1]]) # size of the table

# Now need to score them!

scoretable<-scorepossibleparents(parenttable,n) 

##############
iterations<-100 #number of iterations in the chain
# Choose the probability of the different moves
# 1 is swap any two elements
# 2 is to only swap adjacent elements
# 3 is to stay still (officially needed for convergence)
	prob1<-99
	if(n>3){ prob1<-round(6*99*n/(n^2+10*n-24)) }
	prob1<-prob1/100
	moveprobs<-c(prob1,0.99-prob1,0.01)
	moveprobs<-moveprobs/sum(moveprobs) # normalisation
##############
stepsave=1	
	
example<-orderMCMC(n,startorder,iterations,stepsave,parenttable,scoretable,moveprobs)
iter=30
example[[1]][[iter]]
example[[2]][[iter]]
example[[3]][[iter]]
example[[4]][[iter]]
```
