---
title: "Run function-structureMCMC"
author: "Shengtong"
date: "2018-11-06"
output: workflowr::wflow_html
---



This function-structureMCMC returns the incidence matrix and its corresponding number of edges  in MCMC. 



## pre-req functions 


### listpossibleparents


```{r, echo=T}
combinations=function(n, r, v = 1:n, set = TRUE, repeats.allowed=FALSE)
{
  # n: number if remaining nodes 
  # r: number of parents 
  
  ###### this ensures n is a numeric, scale (length=1), greater than 1 and integer value 
  if(mode(n) != "numeric" || length(n) != 1 
     || n < 1 || (n %% 1) != 0) stop("bad value of n")   # %%: modulus (x mod y) 5%%2 is 1
  ##### same thing for r 
  if(mode(r) != "numeric" || length(r) != 1 
     || r < 1 || (r %% 1) != 0) stop("bad value of r") 
  #print(v)
  
  if(!is.atomic(v) || length(v) < n)  # ensure v is atomic and of the same length as n 
    stop("v is either non-atomic or too short")
  
  if( (r > n) & repeats.allowed==FALSE)  # number of maxparents MUST NOT exceed the remaining elements 
    stop("r > n and repeats.allowed=FALSE")
  
  if(set) {                               # always run this by the initial settings 
    v <- unique(sort(v))
    if (length(v) < n) stop("too few different elements") # again ensure length(v) is equal to n 
  }   # end of set 
  v0 <- vector(mode(v), 0)
  ## Inner workhorse
  if(repeats.allowed)
    sub <- function(n, r, v)
      { 
        if(r == 0) v0 else
        if(r == 1) matrix(v, n, 1) else
        if(n == 1) matrix(v, 1, r) else
        rbind( cbind(v[1], Recall(n, r-1, v)),
              Recall(n-1, r, v[-1]))
      }
  else
    ######################  ????? 
    sub <- function(n, r, v)  
      { 
        if(r == 0) v0 else  # no parents 
        if(r == 1) matrix(v, n, 1) else  # one parent 
        if(r == n) matrix(v, 1, n) else  # maximum number of parents 
        rbind(cbind(v[1], Recall(n-1, r-1, v[-1])),
              Recall(n-1, r, v[-1]))
    }
  
  sub(n, r, v[1:n])
}

listpossibleparents=function(maxparents,elements){

  listy<-vector("list",length(elements)) # generare a list with length of length(elements)

  for (i in elements){
    remainingelements<-elements[-i]

    matrixofparents<-rep(NA,maxparents)  
    for (r in 1:maxparents){
      possparents<-combinations(length(remainingelements),r,remainingelements)
      if(r<maxparents){
        for (j in 1:(maxparents-r)){
	  possparents <- cbind(possparents, NA)
        }
      }
    matrixofparents<-rbind(matrixofparents,possparents,deparse.level=0)
    } # end of r 
    
  listy[[i]] <- matrixofparents
  }   # end of i 

return(listy)
}
```


### scorepossibleparents


```{r, echo=T}
DAGcorescore=function(j,parentnodes,n){
  
  lp<-length(parentnodes) #number of parents
  return(lp)
}

TableDAGscore=function(parentrows, j, n){
	nrows<-nrow(parentrows)
	P_local <- numeric(nrows)   
   
	for (i in 1:nrows)  {
		parentnodes <- parentrows[i,which(parentrows[i,]>0)] # for every row, extract numeric values as parents 
		P_local[i]<-DAGcorescore(j,parentnodes,n)  # DAGcorescore is in numedgescore.R 
	}

return(P_local)
}

scorepossibleparents=function(parenttable,n){

  listy<-vector("list",n)

  for (j in 1:n){
    scoretemp<-TableDAGscore(parenttable[[j]], j, n)      # TableDAGscore is in scorefns.R 
    listy[[j]] <- as.matrix(scoretemp)
  }  

return(listy)

}
```

### propersample

```{r, echo=T}
# randomly sample the node
propersample=function(x)
{if(length(x)==1) x else sample(x,1)}
```



```{r, echo=T}
# what is the purpose of this function??? 
top_order=function(incidence){
Order <- numeric(n)
fan_in <- numeric(n)
no_fan_in <- numeric(0)
m <- 1
for (p in 1:n){                                       # number of parent nodes at the beginning
fan_in[p] <- sum(incidence[,p])
}
no_fan_in <- which(fan_in==0)
while (length(which(Order==0))>0){                    # as long as there is a node without an order
fan_in[which(incidence[no_fan_in[1],]==1)] <- fan_in[which(incidence[no_fan_in[1],]==1)] - 1
no_fan_in <- c(no_fan_in, c(which(incidence[no_fan_in[1],]==1),which(fan_in==0))[duplicated(c(which(incidence[no_fan_in[1],]==1),which(fan_in==0)))])
Order[m] <- no_fan_in[1]
no_fan_in <- no_fan_in[-1]
m <- m+1
}
return(Order)
}
```



```{r, echo=T}
des_top_order=function(incidence, ancest1,child){
top <- top_order(incidence)
position_child <- which(top==child)
top_all_after <- top[position_child:n]                # top. order without the "first" nodes
desc <- which(ancest1[,child]==1)                     # descendants of the child
inter_step <- c(child,desc,top_all_after)
des_top <- inter_step[which(duplicated(inter_step))]
return(des_top)
}
```


### DAGnodescore

```{r,echo=T}
DAGnodescore=function(incidence, n, rescorenodes){
	P_local <- numeric(n)   
   
	for (j in rescorenodes)  {
		parentnodes <- which(incidence[,j]==1)
    P_local[j]<-DAGcorescore(j,parentnodes,n)
	}
		
return(P_local)
}
```


### ancestor

```{r, echo=T}
ancestor=function(incidence){
incidence1 <- incidence
incidence2 <- incidence
k <- 1
while (k < nrow(incidence)){
incidence1 <- incidence1%*%incidence
incidence2 <- incidence2 + incidence1
k <-k+1
}
incidence2[which(incidence2[,]>0)] <- 1
return(t(incidence2))}
```


## structureMCMC

```{r, echo=T}
# this code is taken from the Dortmund course programmed by Miriam Lohr
# I have only changed the scoring function to be correct
# replaced sample by 'propersample'
# and corrected the fan.in for edge reversal!

# The possibility of the new edge reversal move is also built in
# It is activated as long as moveprobs has two components
# The second being the probability of choosing the new edge reversal

# Standard edge reversal can also be toggled with 'revallowed'

structureMCMC <- function(n,incidence,iterations,stepsave,fan.in,parenttable,scoretable,revallowed,moveprobs){

  ###############
  incidence=startDAG
  ###############
  
  newedgerevallowed<-1 # allow the new edge reversal moves
  if(length(moveprobs)==1){
    newedgerevallowed<-0 # or don't allow them
    chosenmove<-1 
  }

  currentDAGlogscores<-DAGnodescore(incidence, n, c(1:n)) # count the number of parents; offspring nodes are in columns and parents in rows in incidence matrix 
  
  #currentDAGlogscores<-DAGscorefromtable(incidence,n,c(1:n),parenttable,scoretable) # or from the table of scores
  currentDAGlogscore<-sum(currentDAGlogscores) # total number of parents 

  L1 <- list() #stores the adjecency matrices
  L2 <- list() # stores the log BGe score of the DAGs

  zlimit<- floor(iterations/stepsave) + 1 # number of outer iterations
  length(L1) <- zlimit
  length(L2) <- zlimit

  L1[[1]]<-incidence #starting adjacency matrix
  L2[[1]]<-currentDAGlogscore #starting DAG score

# first ancestor matrix
  ancest1 <- ancestor(incidence)    # find ancestors for every node  

####### ... the number of neighbour graphs/proposal probability for the FIRST graph
### 1.) number of neighbour graphs obtained by edge deletions
  num_deletion <- sum(incidence)

  emptymatrix<-matrix(numeric(n*n),nrow=n)
  fullmatrix<-matrix(rep(1,n*n),nrow=n)
  Ematrix<-diag(1,n,n)

### 2.) number of neighbour graphs obtained by edge additions    1- E(i,j) - I(i,j) - A(i,j)
  fan.in=maxparents
  inter_add <- which(fullmatrix - Ematrix - incidence - ancest1 >0) # why need to -ancest1 ? because ancestor positions are occupied, not available for adding  edges 
  add <- emptymatrix
  add[inter_add] <- 1
  add[,which(colSums(incidence)>fan.in-1)] <- 0  ### what is here ? subject to maxparents constraint, yes, if that node already has maximum number of parents, it is not allowed to add more edges  
  num_addition <- sum(add)

### 3.) number of neighbour graphs obtained by edge reversals    I - (I^t * A)^t  why is it that? 
  inter_rev <- which(incidence - t(t(incidence)%*% ancest1)==1)
  re <- emptymatrix
  re[inter_rev] <- 1
  re[which(colSums(incidence)>fan.in-1),] <- 0 # this has to be this way around
  num_reversal <- sum(re)

##### total number of neighbour graphs:
  currentnbhoodnorevs <- sum(num_deletion,num_addition)+1
  currentnbhood <- currentnbhoodnorevs+num_reversal

  for (z in 2:zlimit){
    for (count in 1:stepsave){

      if(newedgerevallowed>0){ # if we allow the new edge reversal move then sample the move type	
        chosenmove<-sample.int(2,1,prob=moveprobs) # sample what type of move
      }
      #############################
      #############################
      ## begin switch
      switch(as.character(chosenmove),
###############################
###############################
## begin "1"
      "1"={ # standard structure MCMC

### sample one of the three single edge operations
	if(revallowed==1){
	  operation<-sample.int(4,1,prob=c(num_reversal,num_deletion,num_addition,1)) # sample the type of move including staying still; each type is sampled with the probability proportional to its number of neighbors
	} else {
	  operation<-sample.int(3,1,prob=c(num_deletion,num_addition,1))+1 # sample the type of move including staying still
	}

# 1 is edge reversal, 2 is deletion and 3 is additon. 4 represents choosing the current DAG !!!!!!!

  if(operation<4){ # if we don't stay still

#### shifting of the incidence matrix
	incidence_new <- incidence

# creating a matrix with dimensions of the incidence matrix and all entries zero except for the entry of the chosen edge
	help_matrix <- emptymatrix

	if (operation==2){              # if edge deletion was sampled
	  new_edge <- propersample(which(incidence>0)) # sample one of the existing edges
	  incidence_new[new_edge] <- 0            # and delete it
	  help_matrix[new_edge] <- 1
	}
	if (operation==1){    # if edge reversal was sampled
	  ########### re and add are previously defined 
	  new_edge <- propersample(which(re==1))      # sample one of the existing edges where a reversal leads to a valid graph
	  incidence_new[new_edge] <- 0             # delete it
  	  help_matrix[new_edge] <- 1               # an only a "1" at the entry of the new (reversed) edge
	  incidence_new <- incidence_new + t(help_matrix) # sum the deleted matrix and the "help-matrix"
	}
	if (operation==3){     # if edge addition was sampled
	  new_edge <- propersample(which(add==1)) # sample one of the existing edges where a addition leads to a valid graph
	  incidence_new[new_edge] <- 1             # and add it
	  help_matrix[new_edge] <- 1
	}

### Updating the ancestor matrix

# numbers of the nodes that belong to the shifted egde
	parent <- which(rowSums(help_matrix)==1)
	child <- which(colSums(help_matrix)==1)

### updating the ancestor matrix (after edge reversal)
## edge deletion
	ancestor_new <- ancest1
	if (operation==1){                                                                          
	  ancestor_new[c(child,which(ancest1[,child]==1)),] <- 0   # delete all ancestors of the child and its descendants                                           
	  top_name <- des_top_order(incidence_new, ancest1, child)
	  for (d in top_name){
	    for(g in which(incidence_new[,d]==1)) {
		ancestor_new[d,c(g,(which(ancestor_new[g,]==1)))] <- 1
	    }
	  }

	  anc_parent <- which(ancestor_new[child,]==1)          # ancestors of the new parent
	  des_child <- which(ancestor_new[,parent]==1)          # descendants of the child
	  ancestor_new[c(parent,des_child),c(child,anc_parent)] <- 1
	}

### updating the ancestor matrix (after edge deletion)
	if (operation==2){
	  ancestor_new[c(child,which(ancest1[,child]==1)),] <- 0   # delete all ancestors of the child and its descendants                                           #
	  top_name <- des_top_order(incidence_new, ancest1, child)
	  for (d in top_name){
	    for(g in which(incidence_new[,d]==1)) {
		ancestor_new[d,c(g,(which(ancestor_new[g,]==1)))] <- 1
	    }
	  }
	}

# updating the ancestor matrix (after edge addition)
	if (operation==3){
	  anc_parent <- which(ancest1[parent,]==1)             # ancestors of the new parent
	  des_child <- which(ancest1[,child]==1)               # descendants of the child
	  ancestor_new[c(child,des_child),c(parent,anc_parent)] <- 1
	}

####### ... the number of neighbour graphs/proposal probability for the proposed graph
### 1.) number of neighbour graphs obtained by edge deletions
	num_deletion_new <- sum(incidence_new)

### number of neighbour graphs obtained by edge additions    1- E(i,j) - I(i,j) - A(i,j)
	inter_add.new <- which(fullmatrix - Ematrix - incidence_new - ancestor_new >0)
	add.new <- emptymatrix
	add.new[inter_add.new] <- 1
	add.new[,which(colSums(incidence_new)>fan.in-1)] <- 0
	num_addition_new <- sum(add.new)

### number of neighbour graphs obtained by edge reversals    I - (I^t * A)^t
	inter_rev.new<- which(incidence_new - t(t(incidence_new)%*% ancestor_new)==1)
	re.new <- emptymatrix
	re.new[inter_rev.new] <- 1
	re.new[which(colSums(incidence_new)>fan.in-1),] <- 0 # this has to be this way around!
	num_reversal_new <- sum(re.new)

##### total number of neighbour graphs:
	proposednbhoodnorevs<-sum(num_deletion_new, num_addition_new) + 1
	proposednbhood <- proposednbhoodnorevs + num_reversal_new

	rescorenodes <- child

	if (operation==1){                      # if single edge operation was an edge reversal
	  rescorenodes<-c(child,parent)
	}

  proposedDAGrescored<-DAGnodescore(incidence_new, n, rescorenodes) # rescore relevant nodes directly
	#proposedDAGrescored<-DAGscorefromtable(incidence_new, n, rescorenodes,parenttable,scoretable) # or from the score table
	proposedDAGlogscore<-currentDAGlogscore-sum(currentDAGlogscores[rescorenodes])+sum(proposedDAGrescored[rescorenodes]) #and the new log total score by updating only the necessary nodes

	if(revallowed==1){
	  scoreratio<-exp(proposedDAGlogscore-currentDAGlogscore)*(currentnbhood/proposednbhood) #acceptance probability
	} else{
	  scoreratio<-exp(proposedDAGlogscore-currentDAGlogscore)*(currentnbhoodnorevs/proposednbhoodnorevs) #acceptance probability
	}

	if(runif(1)<scoreratio){ #Move accepted then set the current order and scores to the proposal
	  incidence <- incidence_new
	  currentDAGlogscores[rescorenodes]<-proposedDAGrescored[rescorenodes]
	  currentDAGlogscore<-proposedDAGlogscore
	  ancest1 <- ancestor_new
	  currentnbhood<-proposednbhood
	  currentnbhoodnorevs<-proposednbhoodnorevs	
	  num_deletion <- num_deletion_new
	  num_addition <- num_addition_new
	  num_reversal <- num_reversal_new
	  add <- add.new
	  re <- re.new
	}
  }  # end of staying still loop
      },  # end of "1"
#########################################
#########################################
      "2"={ # new edge reversal move
	testy<-newedgereversalmove(n,incidence,parenttable,scoretable)
	if(is.list(testy)){ # if move was accepted
	  incidence<-testy$incidence # update the matrix
    rescorenodes<-testy$rescore # the child and parent which were swapped
	  currentDAGlogscores[rescorenodes]<-DAGnodescore(incidence, n, rescorenodes)[rescorenodes]
	  currentDAGlogscore<-sum(currentDAGlogscores) # score of incidence matrix 

# The new ancestor matrix
    ancest1<-testy$ancestor

####### ... the number of neighbour graphs/proposal probability for the FIRST graph
### 1.) number of neighbour graphs obtained by edge deletions
	  num_deletion <- sum(incidence)

### 2.) number of neighbour graphs obtained by edge additions    1- E(i,j) - I(i,j) - A(i,j)
	  inter_add <- which(fullmatrix - Ematrix - incidence - ancest1 >0)
	  add <- emptymatrix
	  add[inter_add] <- 1
	  add[,which(colSums(incidence)>fan.in-1)] <- 0
	  num_addition <- sum(add)

### 3.) number of neighbour graphs obtained by edge reversals    I - (I^t * A)^t
	  inter_rev <- which(incidence - t(t(incidence)%*% ancest1)==1)
	  re <- emptymatrix
	  re[inter_rev] <- 1
	  re[which(colSums(incidence)>fan.in-1),] <- 0 # and correct here too!
	  num_reversal <- sum(re)

##### total number of neighbour graphs:
	  currentnbhoodnorevs <- sum(num_deletion,num_addition) + 1
	  currentnbhood <- currentnbhoodnorevs + num_reversal
	}
      },
      {# if neither is chosen, we have a problem
	    print('The move sampling has failed!')
      })  # end of switch
      ###################################
      ###################################
    }
	
  L1[[z]] <- incidence
  L2[[z]] <- currentDAGlogscore 
  }  # end of z
  
return(list(L1,L2))
}

################################################################################


```


## examples 

### consider standard structure MCMC 

```{r, echo=T,eval=T}
n=3  # n nodes 
seedset=1
seednumber=101

maxparents=2

parenttable<-listpossibleparents(maxparents,c(1:n))
tablelength<-nrow(parenttable[[1]]) # size of the table

# Now need to score them!

scoretable<-scorepossibleparents(parenttable,n) 

#"1"={ # standard structure MCMC
	iterations<-100 #number of iterations in the chain
	moveprobs<-c(1) # having length 1 disallows the new edge reversal move
#	if(!(length(moveprobs)==1)){print('Vector of move probabilities has the wrong length!')}
#}
	startDAG<-matrix(numeric(n*n),nrow=n) # starting DAG is empty say
    revallowed<-1 # allow standard edge reversals
    #############
    stepsave<-1 #stepsave<-iterations/1000 #how often to save the result

  if(seedset>0){
    set.seed(seednumber) # choose one?
  }
  #################
    

  example<-structureMCMC(n,startDAG,iterations,stepsave,maxparents,parenttable,scoretable,revallowed,moveprobs)
  
```


